### ISSUE TITLE
[1.13.2] Add Suggestions for String command arguments

### ISSUE THREAD

**Issue by The-Fireplace** [The-Fireplace-Minecraft-Mods/Grand-Exchange#1]
Things like Item ID can be suggested to the player. Theoretically, NBT can also be suggested when looking to buy or sell an item because you can look through opposite typed offers and see what NBT options there are for the item being transacted.

**Comment by kreezxil** [comment]
add this to 1.12.2 too

need also tab completion
need also better help
need to be able to /ge help <subcommand>

**Comment by The-Fireplace** [comment]
New dedicated issue for the help command improvements: #5
