### ISSUE TITLE
/ge collect for beds does not work - beds get converted into air

### ISSUE THREAD

**Issue by Tophattingson** [The-Fireplace-Minecraft-Mods/Grand-Exchange#26]
**Describe the bug**
Repeat of https://github.com/The-Fireplace-Minecraft-Mods/Grand-Exchange/issues/18 but I can add information about what it does to the exchange database.

**To Reproduce**
1. Create an offer to sell a bed.
2. Cancel the offer.
3. Attempt to collect the bed.
4. "You have run out of room for collection. Make room in your inventory and try again."

**Logs/Screenshots/Videos**
The data present in the exchange database all but confirms the cause of this error. It appears that beds get converted into the air block when waiting for collection. As you cannot hold an air block, this presents an obvious error when you try to collect it.

`{
  "offers": [],
  "payouts": [
    {
      "user": "086b4ebf-5117-4c67-88cb-b249f4f0eea6",
      "items": [
        "{id:\"minecraft:air\",Count:1b,Damage:0s}"
      ]
    }
  ],
  "next_identifier": 4,
  "partial_offer_status_updates": [],
  "complete_offer_status_updates": []
}`

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.12.2
 - Mod Version: 1.12.2-1.3.1
 - Forge (If applicable) 1.12.2-14.23.5.2768-universal

**Comment by The-Fireplace** [comment]
Confirmed in GEx 1.4.0
