### ISSUE TITLE
Need actual menu

### ISSUE THREAD

**Issue by kreezxil** [The-Fireplace-Minecraft-Mods/Grand-Exchange#3]
When use /ge buyoffers, selloffers, etc where a list of data is displayed in chat that can be paged a list of information similar to what you might find when using the /mc colonies list command from minecolonies would be very useful.

The minecolonies command for reference:
![Screenshot_2](https://user-images.githubusercontent.com/3880072/57186297-5321eb80-6ea2-11e9-8519-f51a205eee93.png)

As you can see each entry has an id plus a little bit of data like a name for instance and at the bottom is previous and next which can be click on to advance the pages in either direction.

Grand Exchange needs this ability. Instead of showing all of the horrid data associated with an entry, it should have something like the following:

ID, SHORT NAME, PRICE EACH, QTY AVAILABLE

when the player wants to cancel an item they can use the ID

if they want to buy an item they again use the ID

the rest of your command should probably stay the same.

**Comment by The-Fireplace** [comment]
Not a bad idea. Will probably get this done after I establish a template for this when working on The-Fireplace-Minecraft-Mods/Clans#106

**Comment by kreezxil** [comment]
Do you have place for sending incentives? I need to encourage you to code
more because for one you're the reason I even got into it in the first
place.
