### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by cutethingg** [The-Fireplace-Minecraft-Mods/Grand-Exchange#38]
posted about this on the discord but thought I would post here as well. 

When preforming commands in Grand Exchange (specifically `/ge sellthis [amount] [price]`), I receive the error:
`Error occurred while executing command: java.lang.NoClassDefFoundError:the_fireplace/clans/cache/ClanCache` 
in the chat. I didn't notice any additional outputs in the console. In addition, any admin-command-sold/bought items do not appear on the sell or buy market lists.

If it helps, I also have the latest versions of Clans and Grand Economy, I am also using the latest spongeforge and LuckPerms (though all perms were setup correctly).

Thank you in advance, I look forward to integrating Grand Exchange fully into my server :)

**Comment by The-Fireplace** [comment]
Fixed in GEx 1.5.2
