### ISSUE TITLE
Allow for credits to be given over time

### ISSUE THREAD

**Issue by dmh3333** [The-Fireplace-Minecraft-Mods/Grand-Exchange#4]
In the config for the mod, there should be an option to give credits every certain amount of minutes/hours or some unit of time. I currently use 1.12.2, so I would hope the update could come out for that version. Enderpay has this feature and since Enderpay is not compatible with the Clan's mod it would be a nice feature to have.

**Comment by The-Fireplace** [comment]
EnderPay is now compatible as of Grand Economy 1.2.0 Alpha 1. In addition, GE can give credits daily.
