### ISSUE TITLE
Possibility to create SERVER CONTROLLED TRADES with limited and unlimited quantities

### ISSUE THREAD

**Issue by Turacs** [The-Fireplace-Minecraft-Mods/Grand-Exchange#8]
The shops could function the same as the previous ones, only with the difference that the **sales were created on the server by an admin** (via CLI command or much better: Stock Config file with trades as JSON, XML or CSV ??)
It would also be great if the sales could be offered in limited or unlimited quantities.

Thank you for your consideration.

**Comment by The-Fireplace** [comment]
Grand Exchange 1.4.0 for 1.12.2 is now available on Patreon! It will be on CurseForge 4/4/20. Changes include sales tax, server-controlled infinite shops, control over what you collect, and integration with Sponge & Forge-based permission managers. Enjoy!
https://www.patreon.com/posts/35132258
